### PR TITLE
Npm publish setup

### PR DESCRIPTION
**Pull request by prozacchiwawa**

### CODE REVIEW

**Comment by prozacchiwawa** [comment]
Pulls in the npm setup from language server so it can be separately landed here
this will allow us to test wasm publishing

**Review by ChiaMineJP — DISMISSED** [review]
lgtm

**Comment by ChiaMineJP** [comment]
It seems rebasing is required.
@prozacchiwawa Do you want me to rebase and force push?

**Comment by prozacchiwawa** [comment]
Apologies, i merged up from base after the srcloc change supporting the language server.

**Review by AmineKhaldi — APPROVED** [review]

**Pull request merged**
