### PR TITLE
candidate fix for https://github.com/Chia-Network/clvm_tools/issues/83

### PR DESCRIPTION
**Pull request by prozacchiwawa**

### CODE REVIEW

**Review by trepca — DISMISSED** [review]
resolves the issue for me

**Review by arvidn — COMMENTED** [review]
it's really hard to review with all the clippy warnings. Did you add a unit test to cover this issue? There's quite a lot of new code, so I would expect we need more than one new test case to cover it.

**Comment by prozacchiwawa** [comment]
Apologies, merged up the clippy branch so these shouldn't be as noisy.

**Review by arvidn — COMMENTED** [review]
I really think there should be a test demonstrating the issue with the old code and demonstrating that the new code yields the correct result.

**Comment by prozacchiwawa** [comment]
The problem here is that the issue is it runs very slowly.
This code must not change anything about the output (it's frozen) so i'm unsure how to demonstrate it in a test.  I can put in a cache disable and measure wallclock time I suppose.

**Comment by prozacchiwawa** [comment]
how would everyone feel about a queryable cache hit metric that can be checked after compilation? (as a test)

**Comment by arvidn** [comment]
> The problem here is that the issue is it runs very slowly.
> This code must not change anything about the output (it's frozen) so i'm unsure how to demonstrate it in a test. I can put in a cache disable and measure wallclock time I suppose.

You're saying this is fixing a performance issue, not a correctness issue?

Reading the ticket you refer to in the title ( https://github.com/Chia-Network/clvm_tools/issues/83 ) it seems to be talking about mis-compilation (which I would expect it would be easy to unit test)

**Comment by arvidn** [comment]
oh, I see that's also in the `clvm_tools` repository. so perhaps we don't have that issue here, just the performance.

**Comment by prozacchiwawa** [comment]
ahh sorry, was thinking of the other one
apologies

**Comment by prozacchiwawa** [comment]
This comment is a test of my filtering change to prioritize messages from this repo.

**Review by arvidn — APPROVED** [review]

**Review by trepca — APPROVED** [review]

**Pull request merged**
