### PR TITLE
20220814 fmt

### PR DESCRIPTION
**Pull request by prozacchiwawa**
Add a simple, straight through formatter for chialisp.
It is opinionated:
 - 2 space indent
 - indents each line but does no other modification
 - aligns subsequent lines inside (if .. with the condition
Comments are mostly gnu style but:
- ; comments are treated as ;; if they appear on an empty line
- any ;;; or ;;;; comments after a line are put on a line of their own before the code
- when ; comments appear after code, the group of them, until no comment is found, is aligned to the largest right spacing needed
These rules can be modified if desired after it's tried out.
Code between the first nonblank, non-semicolon and the last character that is neither a blank or semicolon is not modified.

### CODE REVIEW

**Comment by trepca** [comment]
Good progress!

It'd be good to have `-h` or `--help` to explain how to use it. Not sure about creating `.new` files, pretty prints usually takes either stdin or a filename and outputs formatted file to stdout. What's the reasoning behind `.new` files? 

I tried formatting:
```
(mod (a b c) (defun func (arg)
    ( f (

        list arg))
    )

  (func (+ a b c)
    ))
```
but it didn't work. It did work for some standard puzzles though. 

A set of chialisp file fixtures with before and after (formatting) file would be helpful for maintenance so we can ensure integrity of the formatter as it's updated.

**Review by arvidn — COMMENTED** [review]
it would be really nice to add some tests demonstrating all the kinds of transforms this makes.

Also, I would have imagined lisp being very suitable to completely parse into an AST and then print it out. The only complication would be comments. I would welcome a formatter that doesn't just indent, but also breaks and joins lines, to produce a truly canonical formatting of a program, no matter its initial formatting.

**Comment by prozacchiwawa** [comment]
regarding the example, I likely need to set clear expectations, it absolutely did what this formatter is supposed to do, although maybe a more intrusive approach is desired.  i wanted to be very conservative and have a soft touch, so it doesn't change code between the first nonblank and the last nonblank of any line before a comment.

I can do a second pass on this if we want to enforce a more opinionated style beyond that.

**Comment by arvidn** [comment]
it's virtually impossible to manually inspect the code and assert that it's correct. I think it would be good to have examples of the transforms performed in CI. With some intput code and ensure the output is what we would expect.

I could check this out and try it on a few examples by hand, but that won't ensure this code doesn't break under future refactors.

**Pull request closed without merging**
